modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20GUI%20Clock"
logoFile="icon.png"

[[mods]]
modId="guiclock"
version="4.4"
displayName="GUI Clock"
displayURL="https://serilum.com/mod/gui-clock"
authors="Rick South"
description='''Shows the time and days played in the GUI on the screen with a clock in the inventory.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.guiclock]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.guiclock]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "guiclock_neoforge.mixins.json"